<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="7" total="8" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="tests.DropdownsTest" duration-ms="26393" started-at="2020-02-09T00:33:00 UYT" finished-at="2020-02-09T00:33:26 UYT">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="26393" started-at="2020-02-09T00:33:00 UYT" finished-at="2020-02-09T00:33:26 UYT">
      <class name="tests.DropdownsTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DropdownsTest@42dafa95]" name="setUp" is-config="true" duration-ms="19407" started-at="2020-02-09T00:33:00 UYT" finished-at="2020-02-09T00:33:19 UYT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="getReady()[pri:0, instance:tests.DropdownsTest@42dafa95]" name="getReady" is-config="true" duration-ms="4417" started-at="2020-02-09T00:33:19 UYT" finished-at="2020-02-09T00:33:23 UYT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getReady -->
        <test-method status="FAIL" signature="option2()[pri:0, instance:tests.DropdownsTest@42dafa95]" name="option2" duration-ms="291" started-at="2020-02-09T00:33:23 UYT" description="Test de Dropdowns - opcion Price Lowest first " finished-at="2020-02-09T00:33:24 UYT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [position:asc] but found [price:asc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [position:asc] but found [price:asc]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.DropdownsTest.option2(DropdownsTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- option2 -->
        <test-method status="PASS" signature="close(org.testng.ITestResult)[pri:0, instance:tests.DropdownsTest@42dafa95]" name="close" is-config="true" duration-ms="2229" started-at="2020-02-09T00:33:24 UYT" finished-at="2020-02-09T00:33:26 UYT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=option2 status=FAILURE method=DropdownsTest.option2()[pri:0, instance:tests.DropdownsTest@42dafa95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- tests.DropdownsTest -->
    </test> <!-- Command line test -->
  </suite> <!-- tests.DropdownsTest -->
</testng-results>
